<?php

namespace Listreat\ApiBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ShopController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Listreat\ApiBundle\Controller\ShopController();
        return $instance;
    }
}
