<?php

namespace Listreat\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FriendRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FriendRepository extends EntityRepository
{
    public function getFriendsList($user)
    {
        $query = $this->getEntityManager()->createQuery(
              'SELECT f, u FROM ListreatUserBundle:Friend f INNER JOIN f.friend u WHERE f.user = :user ORDER BY u.id DESC'
              )->setParameter('user', $user->getId());
        return $query->getResult();
    }
}
